// Datos geográficos de Argentina: zona → partidos → localidades
const GEO_DATA = {
  'Capital Federal': {
    partidos: [
      'Agronomía','Almagro','Balvanera','Barracas','Belgrano','Boedo','Caballito',
      'Chacarita','Coghlan','Colegiales','Constitución','Flores','Floresta','La Boca',
      'La Paternal','Liniers','Mataderos','Microcentro','Monte Castro','Montserrat',
      'Nueva Pompeya','Núñez','Palermo','Parque Avellaneda','Parque Chacabuco',
      'Parque Chas','Parque Patricios','Puerto Madero','Recoleta','Retiro','Saavedra',
      'San Cristóbal','San Nicolás','San Telmo','Vélez Sársfield','Versalles',
      'Villa Crespo','Villa del Parque','Villa Devoto','Villa General Mitre',
      'Villa Lugano','Villa Luro','Villa Ortúzar','Villa Pueyrredón','Villa Real',
      'Villa Riachuelo','Villa Santa Rita','Villa Soldati','Villa Urquiza',
    ],
    localidades: {
      'Agronomía':['Agronomía'],'Almagro':['Almagro'],'Balvanera':['Balvanera'],
      'Barracas':['Barracas'],'Belgrano':['Belgrano','Belgrano C','Belgrano R'],
      'Boedo':['Boedo'],'Caballito':['Caballito'],'Chacarita':['Chacarita'],
      'Coghlan':['Coghlan'],'Colegiales':['Colegiales'],'Constitución':['Constitución'],
      'Flores':['Flores'],'Floresta':['Floresta'],'La Boca':['La Boca'],
      'La Paternal':['La Paternal'],'Liniers':['Liniers'],'Mataderos':['Mataderos'],
      'Microcentro':['Microcentro'],'Monte Castro':['Monte Castro'],'Montserrat':['Montserrat'],
      'Nueva Pompeya':['Nueva Pompeya'],'Núñez':['Núñez'],
      'Palermo':['Palermo','Palermo Chico','Palermo Hollywood','Palermo Soho','Palermo Nuevo'],
      'Parque Avellaneda':['Parque Avellaneda'],'Parque Chacabuco':['Parque Chacabuco'],
      'Parque Chas':['Parque Chas'],'Parque Patricios':['Parque Patricios'],
      'Puerto Madero':['Puerto Madero'],'Recoleta':['Recoleta'],'Retiro':['Retiro'],
      'Saavedra':['Saavedra'],'San Cristóbal':['San Cristóbal'],'San Nicolás':['San Nicolás'],
      'San Telmo':['San Telmo'],'Vélez Sársfield':['Vélez Sársfield'],'Versalles':['Versalles'],
      'Villa Crespo':['Villa Crespo'],'Villa del Parque':['Villa del Parque'],
      'Villa Devoto':['Villa Devoto'],'Villa General Mitre':['Villa General Mitre'],
      'Villa Lugano':['Villa Lugano'],'Villa Luro':['Villa Luro'],
      'Villa Ortúzar':['Villa Ortúzar'],'Villa Pueyrredón':['Villa Pueyrredón'],
      'Villa Real':['Villa Real'],'Villa Riachuelo':['Villa Riachuelo'],
      'Villa Santa Rita':['Villa Santa Rita'],'Villa Soldati':['Villa Soldati'],
      'Villa Urquiza':['Villa Urquiza'],
    },
  },
  'Buenos Aires': {
    partidos: [
      'Almirante Brown','Avellaneda','Azul','Bahía Blanca','Balcarce','Baradero',
      'Berazategui','Berisso','Bolívar','Bragado','Brandsen','Campana','Cañuelas',
      'Chacabuco','Chascomús','Chivilcoy','Colón','Ensenada','Escobar',
      'Esteban Echeverría','Exaltación de la Cruz','Ezeiza','Florencio Varela',
      'General Alvarado','General Belgrano','General Pueyrredón','General Rodríguez',
      'General San Martín','Hipólito Yrigoyen','Hurlingham','Ituzaingó','José C. Paz',
      'Junín','La Costa','La Matanza','La Plata','Lanús','Las Flores','Lincoln',
      'Lobos','Lomas de Zamora','Luján','Malvinas Argentinas','Mar Chiquita',
      'Marcos Paz','Mercedes','Merlo','Monte Hermoso','Moreno','Morón',
      'Navarro','Necochea','Nueve de Julio','Olavarría','Pergamino','Pilar',
      'Pinamar','Presidente Perón','Quilmes','Ramallo','San Fernando','San Isidro',
      'San Miguel','San Nicolás','San Pedro','San Vicente','Tandil','Tigre',
      'Trenque Lauquen','Tres Arroyos','Tres de Febrero','Vicente López',
      'Villa Gesell','Zárate',
    ],
    localidades: {
      'Almirante Brown':['Adrogué','Burzaco','Claypole','Don Orione','Glew','José Mármol','Longchamps','Malvinas Argentinas','Ministro Rivadavia','Rafael Calzada','San Francisco de Asís'],
      'Avellaneda':['Avellaneda','Crucecita','Dock Sud','Gerli','Piñeyro','Sarandí','Villa Dominico'],
      'Azul':['Azul','Cacharí','Chillar'],
      'Bahía Blanca':['Bahía Blanca','Cabildo','Ingeniero White','Punta Alta'],
      'Balcarce':['Balcarce','Los Pinos','Napaleofú'],
      'Baradero':['Baradero','Ireneo Portela','Villa Alsina'],
      'Berazategui':['Berazategui','Guillermo E. Hudson','Plátanos','Ranelagh','Villa España'],
      'Berisso':['Berisso','Villa Arguello','Villa Nueva'],
      'Bolívar':['Bolívar','Urdampilleta','Pirovano'],
      'Bragado':['Bragado','Mechita','O\'Brien'],
      'Brandsen':['Brandsen','Gómez','Jeppener'],
      'Campana':['Campana','Otamendi'],
      'Cañuelas':['Cañuelas','Gobernador Castro','Máximo Paz'],
      'Chacabuco':['Chacabuco','Castilla','Los Ángeles','Rawson'],
      'Chascomús':['Chascomús','Lezama'],
      'Chivilcoy':['Chivilcoy','Moquehuá'],
      'Colón':['Colón','Los Cardales','Sarandi'],
      'Ensenada':['Ensenada','Punta Lara'],
      'Escobar':['Belén de Escobar','Garín','Ingeniero Maschwitz','Loma Verde','Maquinista F. Savio','Matheu','Open Door'],
      'Esteban Echeverría':['El Jagüel','Luis Guillón','Monte Grande','Tristán Suárez'],
      'Exaltación de la Cruz':['Capilla del Señor','Cardales','Pavón','Villanueva'],
      'Ezeiza':['Carlos Spegazzini','Ezeiza','La Unión'],
      'Florencio Varela':['Bosques','Florencio Varela','Los Eucaliptos','Villa Brown','Villa San Luis'],
      'General Alvarado':['Miramar','Mar del Sud','Mechongué'],
      'General Belgrano':['General Belgrano','Roque Pérez','Gorchs'],
      'General Pueyrredón':['Mar del Plata','Batán','Chapadmalal','Sierra de los Padres'],
      'General Rodríguez':['General Rodríguez','La Lonja','Villanueva'],
      'General San Martín':['El Palomar','José León Suárez','San Martín','Villa Ballester','Villa Lynch','Villa Maipú','Villa Raffo','Villa Sarmiento'],
      'Hipólito Yrigoyen':['Henderson','Smith','Valeria del Mar'],
      'Hurlingham':['Hurlingham','Villa Tesei','William C. Morris'],
      'Ituzaingó':['Ituzaingó','Padre Respuela','Villa del Parque'],
      'José C. Paz':['José C. Paz','La Reja'],
      'Junín':['Junín','Agustina','Morse','Saforcada'],
      'La Costa':['Aguas Verdes','Costa Azul','Las Toninas','Mar de Ajó','Mar del Tuyú','Nueva Atlantis','San Bernardo','San Clemente del Tuyú','Santa Teresita'],
      'La Matanza':['Ciudad Evita','González Catán','Gregorio de Laferrère','Isidro Casanova','La Tablada','Lomas del Mirador','Rafael Castillo','Ramos Mejía','San Justo','Tapiales','Villa Madero','Virrey del Pino'],
      'La Plata':['City Bell','Arturo Seguí','Gonnet','Hernández','La Plata','Los Hornos','Lisandro Olmos','Melchor Romero','Ringuelet','San Carlos','Tolosa','Villa Elisa'],
      'Lanús':['Lanús Este','Lanús Oeste','Monte Chingolo','Remedios de Escalada','Valentín Alsina'],
      'Las Flores':['Las Flores','Pila'],
      'Lincoln':['Lincoln','Arenaza','Pasteur','Roberts'],
      'Lobos':['Lobos','Elvira','General Rojo'],
      'Lomas de Zamora':['Banfield','Ingeniero Budge','Lomas de Zamora','Temperley','Turdera','Villa Centenario'],
      'Luján':['Luján','Carlos Keen','Cortines','Jáuregui','Open Door','Torres'],
      'Malvinas Argentinas':['Grand Bourg','Ingeniero Adolfo Sourdeaux','Ingeniero Pablo Nogués','Los Polvorines','Malvinas Argentinas'],
      'Mar Chiquita':['Coronel Vidal','Mar Chiquita','Mar de Cobo','Santa Clara del Mar'],
      'Marcos Paz':['Marcos Paz','Plomer'],
      'Mercedes':['Mercedes','Gándara','Gowland'],
      'Merlo':['Libertad','Mariano Acosta','Merlo','San Antonio de Padua','Suárez'],
      'Monte Hermoso':['Monte Hermoso'],
      'Moreno':['Cuartel V','Francisco Álvarez','La Reja','Moreno','Trujui'],
      'Morón':['El Palomar','Haedo','Morón','Villa Sarmiento'],
      'Navarro':['Navarro','Álvarez de Toledo'],
      'Necochea':['Necochea','Quequén','Claromecó'],
      'Nueve de Julio':['9 de Julio','Alfredo Demarchi','French','Patricios'],
      'Olavarría':['Olavarría','Hinojo','Sierra Chica','Sierras Bayas'],
      'Pergamino':['Pergamino','Acevedo','Juan Anchorena','Pinzón'],
      'Pilar':['Del Viso','Fatima','Manuel Alberti','Pilar','Presidente Derqui','Villa Rosa'],
      'Pinamar':['Pinamar','Ostende','Valeria del Mar'],
      'Presidente Perón':['Guernica','Alejandro Korn'],
      'Quilmes':['Bernal','Bernal Oeste','Don Bosco','Ezpeleta','Quilmes','San Francisco Solano'],
      'Ramallo':['Ramallo','Villa Ramallo'],
      'San Fernando':['Boulogne','San Fernando','Victoria','Virreyes'],
      'San Isidro':['Acassuso','Beccar','Boulogne','La Horqueta','Martínez','Punta Chica','San Isidro'],
      'San Miguel':['Bella Vista','Muñiz','San Miguel','Santa María'],
      'San Nicolás':['San Nicolás de los Arroyos','La Emilia','Villa Constitución'],
      'San Pedro':['San Pedro','Gobernador Castro','Vuelta de Obligado'],
      'San Vicente':['San Vicente','Alejandro Korn','Domselaar'],
      'Tandil':['Tandil','Gardey','María Ignacia - Vela'],
      'Tigre':['Benavídez','Don Torcuato','El Talar','General Pacheco','Nordelta','Rincón de Milberg','Tigre'],
      'Trenque Lauquen':['Trenque Lauquen','Beruti','Moctezuma'],
      'Tres Arroyos':['Tres Arroyos','Claromecó','Reta'],
      'Tres de Febrero':['Caseros','Ciudadela','Palermo','Sáenz Peña','Santos Lugares','Villa Bosch'],
      'Vicente López':['Carapachay','Florida','Florida Oeste','La Lucila','Munro','Olivos','Vicente López','Villa Adelina','Villa Martelli'],
      'Villa Gesell':['Villa Gesell','Las Gaviotas','Mar de las Pampas','Mar Azul'],
      'Zárate':['Zárate','Lima'],
    },
  },
  'Córdoba': {
    partidos: ['Capital','Colón','General Roca','Juárez Celman','Marcos Juárez','Punilla','Río Cuarto','Río Primero','Río Segundo','Tercero Arriba','Unión','Río Seco','San Alberto','San Javier'],
    localidades: {
      'Capital':['Córdoba','Mendiolaza','Unquillo','Villa Allende','Villa Carlos Paz (acceso)'],
      'Colón':['Colón','Cosquín','Jesús María','Sinsacate','Villa Allende'],
      'General Roca':['General Deheza','Laboulaye','Vicuña Mackenna'],
      'Juárez Celman':['Río Tercero','La Carlota'],
      'Marcos Juárez':['Marcos Juárez','Leones','Bell Ville'],
      'Punilla':['Cosquín','La Cumbre','La Falda','Mina Clavero','Valle Hermoso','Villa Carlos Paz'],
      'Río Cuarto':['Río Cuarto','Las Higueras','Alcira Gigena'],
      'Río Primero':['Capilla del Monte','Oncativo'],
      'Río Segundo':['Alta Gracia','Cañada de Gómez','Pilar'],
      'Tercero Arriba':['Bell Ville','Hernando','Villa del Rosario'],
      'Unión':['San Francisco','Ausonia'],
      'Río Seco':['Seeber'],
      'San Alberto':['Mina Clavero','Villa Cura Brochero'],
      'San Javier':['Villa Dolores'],
    },
  },
  'Santa Fe': {
    partidos: ['La Capital','Rosario','Castellanos','Las Colonias','Iriondo','San Lorenzo','General López','General Obligado','Constitución','San Cristóbal','San Jerónimo','San Martín','Belgrano','Caseros','Garay','Vera'],
    localidades: {
      'La Capital':['Santa Fe','Recreo','Santo Tomé','San José del Rincón'],
      'Rosario':['Rosario','Granadero Baigorria','Pérez','Soldini','Funes','Roldán'],
      'Castellanos':['Rafaela','Sunchales','Esperanza'],
      'Las Colonias':['Esperanza','San Carlos','San Jerónimo del Sauce'],
      'Iriondo':['Cañada de Gómez','Cañada Rosquín'],
      'San Lorenzo':['San Lorenzo','Capitán Bermúdez','Puerto General San Martín'],
      'General López':['Venado Tuerto','Melincué'],
      'General Obligado':['Reconquista','Avellaneda'],
      'Constitución':['Constitución','Villa Constitución'],
      'San Cristóbal':['San Cristóbal'],
      'San Jerónimo':['Gálvez'],
      'San Martín':['Casilda','Cañada de Gómez'],
      'Belgrano':['Las Rosas'],
      'Caseros':['Caseros'],
      'Garay':['Cayastá'],
      'Vera':['Vera'],
    },
  },
  'Mendoza': {
    partidos: ['Capital','General Alvear','Godoy Cruz','Guaymallén','Junín','La Paz','Las Heras','Lavalle','Luján de Cuyo','Maipú','Malargüe','Rivadavia','San Carlos','San Martín','San Rafael','Santa Rosa','Tupungato','Tunuyán'],
    localidades: {
      'Capital':['Mendoza'],
      'General Alvear':['General Alvear'],
      'Godoy Cruz':['Godoy Cruz'],
      'Guaymallén':['Guaymallén','Bermejo','Dorrego'],
      'Junín':['Junín'],
      'La Paz':['La Paz'],
      'Las Heras':['Las Heras','El Challao'],
      'Lavalle':['Lavalle','Costa de Araujo'],
      'Luján de Cuyo':['Luján de Cuyo','Chacras de Coria','Mayor Drummond','Perdriel','Agrelo'],
      'Maipú':['Maipú','Coquimbito','Fray Luis Beltrán','Russell'],
      'Malargüe':['Malargüe'],
      'Rivadavia':['Rivadavia'],
      'San Carlos':['San Carlos','Eugenio Bustos'],
      'San Martín':['San Martín','Palmira'],
      'San Rafael':['San Rafael'],
      'Santa Rosa':['Santa Rosa'],
      'Tupungato':['Tupungato'],
      'Tunuyán':['Tunuyán'],
    },
  },
  'Tucumán': {
    partidos: ['Capital','Burruyacú','Cruz Alta','Famaillá','Graneros','Juan Bautista Alberdi','La Cocha','Leales','Lules','Monteros','Río Chico','Simoca','Tafí del Valle','Tafí Viejo','Trancas','Yerba Buena'],
    localidades: {
      'Capital':['San Miguel de Tucumán'],
      'Cruz Alta':['Alderetes','Banda del Río Salí','Las Talitas'],
      'Tafí Viejo':['Tafí Viejo'],
      'Yerba Buena':['Yerba Buena','El Manantial','Los Nogales'],
      'Lules':['Lules','Raco'],
      'Famaillá':['Famaillá'],
      'Monteros':['Monteros','Acheral'],
      'Tafí del Valle':['Tafí del Valle','El Mollar'],
      'Leales':['Leales'],
      'Burruyacú':['Burruyacú'],
      'Graneros':['Graneros'],
      'Juan Bautista Alberdi':['Juan Bautista Alberdi'],
      'La Cocha':['La Cocha'],
      'Río Chico':['Aguilares'],
      'Simoca':['Simoca'],
      'Trancas':['Trancas'],
    },
  },
  'Salta': {
    partidos: ['Capital','Cafayate','Cerrillos','Chicoana','General Güemes','General José de San Martín','La Caldera','Metán','Orán','Rosario de la Frontera','Rosario de Lerma','Iruya','Los Andes'],
    localidades: {
      'Capital':['Salta','La Caldera'],
      'Cafayate':['Cafayate'],
      'Cerrillos':['Cerrillos'],
      'Chicoana':['Chicoana'],
      'General Güemes':['General Güemes'],
      'General José de San Martín':['Tartagal','Aguaray','General Mosconi'],
      'La Caldera':['La Caldera'],
      'Metán':['Metán'],
      'Orán':['Orán','Pichanal'],
      'Rosario de la Frontera':['Rosario de la Frontera'],
      'Rosario de Lerma':['Rosario de Lerma','Campo Quijano'],
      'Iruya':['Iruya'],
      'Los Andes':['San Antonio de los Cobres'],
    },
  },
  'Jujuy': {
    partidos: ['Dr. Manuel Belgrano','El Carmen','Humahuaca','Ledesma','Palpalá','San Antonio','San Pedro','Santa Bárbara','Tilcara','Tumbaya','Yavi'],
    localidades: {
      'Dr. Manuel Belgrano':['San Salvador de Jujuy'],
      'El Carmen':['El Carmen','Perico'],
      'Palpalá':['Palpalá'],
      'Ledesma':['Libertador General San Martín','Calilegua'],
      'San Pedro':['San Pedro de Jujuy','La Esperanza'],
      'Humahuaca':['Humahuaca'],
      'Tilcara':['Tilcara','Maimará'],
      'Tumbaya':['Volcán','Purmamarca'],
      'Santa Bárbara':['Santa Bárbara'],
      'San Antonio':['Abra Pampa'],
      'Yavi':['La Quiaca','Yavi'],
    },
  },
  'Misiones': {
    partidos: ['Capital','Iguazú','El Dorado','Oberá','Apóstoles','Leandro N. Alem','General Manuel Belgrano','San Ignacio','Guaraní','Candelaria','Concepción','Libertador General San Martín','Montecarlo','San Javier','San Martín','San Pedro','Cainguás'],
    localidades: {
      'Capital':['Posadas','Garupá'],
      'Iguazú':['Puerto Iguazú','Wanda','Puerto Esperanza'],
      'El Dorado':['El Dorado'],
      'Oberá':['Oberá'],
      'Apóstoles':['Apóstoles'],
      'Leandro N. Alem':['Leandro N. Alem','Dos de Mayo'],
      'General Manuel Belgrano':['Bernardo de Irigoyen'],
      'San Ignacio':['San Ignacio','Jardín América'],
      'Guaraní':['El Soberbio'],
      'Candelaria':['Candelaria'],
      'Concepción':['Concepción de la Sierra'],
      'Libertador General San Martín':['Puerto Rico'],
      'Montecarlo':['Montecarlo'],
      'San Javier':['San Javier'],
      'San Martín':['Aristóbulo del Valle'],
      'San Pedro':['San Pedro'],
      'Cainguás':['Campo Viera'],
    },
  },
  'Corrientes': {
    partidos: ['Capital','Goya','Curuzú Cuatiá','Mercedes','Paso de los Libres','Santo Tomé','Esquina','Ituzaingó','Monte Caseros','Bella Vista','Concepción','Saladas','San Roque','Itatí','Lavalle'],
    localidades: {
      'Capital':['Corrientes'],
      'Goya':['Goya'],
      'Curuzú Cuatiá':['Curuzú Cuatiá'],
      'Mercedes':['Mercedes'],
      'Paso de los Libres':['Paso de los Libres'],
      'Santo Tomé':['Santo Tomé'],
      'Esquina':['Esquina'],
      'Ituzaingó':['Ituzaingó','Virasoro'],
      'Monte Caseros':['Monte Caseros'],
      'Bella Vista':['Bella Vista'],
      'Concepción':['Concepción'],
      'Saladas':['Saladas'],
      'San Roque':['San Roque'],
      'Itatí':['Itatí'],
      'Lavalle':['Lavalle'],
    },
  },
  'Entre Ríos': {
    partidos: ['Paraná','Concordia','Gualeguaychú','Gualeguay','Colón','Federación','Victoria','La Paz','Diamante','Nogoyá','Uruguay','Villaguay','San Salvador','Tala','Feliciano','Federal'],
    localidades: {
      'Paraná':['Paraná','Laurencena','General Racedo','Viale'],
      'Concordia':['Concordia'],
      'Gualeguaychú':['Gualeguaychú','Urdinarrain'],
      'Gualeguay':['Gualeguay'],
      'Colón':['Colón','San José'],
      'Federación':['Federación','Villa del Rosario','Chajarí'],
      'Victoria':['Victoria'],
      'La Paz':['La Paz'],
      'Diamante':['Diamante'],
      'Nogoyá':['Nogoyá'],
      'Uruguay':['Concepción del Uruguay'],
      'Villaguay':['Villaguay'],
      'San Salvador':['San Salvador'],
      'Tala':['Rosario del Tala'],
      'Feliciano':['San José de Feliciano'],
      'Federal':['Federal'],
    },
  },
  'Chaco': {
    partidos: ['San Fernando','Comandante Fernández','Mayor Luis Jorge Fontana','General Güemes','Libertador General San Martín','Maipú','Quitilipi','Veinticinco de Mayo','Doce de Octubre','General Belgrano','General Donovan','Nueve de Julio'],
    localidades: {
      'San Fernando':['Resistencia','Barranqueras','Fontana','Puerto Vilelas'],
      'Comandante Fernández':['Presidencia Roque Sáenz Peña'],
      'Mayor Luis Jorge Fontana':['Villa Ángela'],
      'General Güemes':['Juan José Castelli'],
      'Libertador General San Martín':['General José de San Martín'],
      'Maipú':['Maipú'],
      'Quitilipi':['Quitilipi'],
      'Veinticinco de Mayo':['Los Frentones'],
      'Doce de Octubre':['Gancedo'],
      'General Belgrano':['Corzuela'],
      'General Donovan':['Miraflores'],
      'Nueve de Julio':['Las Breñas'],
    },
  },
  'Formosa': {
    partidos: ['Formosa','Pirané','Patiño','Pilcomayo','Bermejo','Laishí','Matacos','Ramón Lista'],
    localidades: {
      'Formosa':['Formosa'],
      'Pirané':['Pirané'],
      'Patiño':['Las Lomitas'],
      'Pilcomayo':['Clorinda'],
      'Bermejo':['General Lucio Victorio Mansilla'],
      'Laishí':['General Enrique Mosconi'],
      'Matacos':['Ingeniero Juárez'],
      'Ramón Lista':['Laguna Yema'],
    },
  },
  'Santiago del Estero': {
    partidos: ['Capital','Banda','Robles','General Taboada','Moreno','Guasayán','Choya','Copo','Jiménez','Mitre','Salavina','San Martín','Sarmiento','Silípica'],
    localidades: {
      'Capital':['Santiago del Estero'],
      'Banda':['La Banda'],
      'Robles':['Frías'],
      'General Taboada':['Añatuya'],
      'Moreno':['Moreno'],
      'Guasayán':['Guasayán'],
      'Choya':['Choya'],
      'Copo':['Monte Quemado'],
      'Jiménez':['Quimilí'],
      'Mitre':['Suncho Corral'],
      'Salavina':['Los Telares'],
      'San Martín':['Bandera'],
      'Sarmiento':['Lavalle'],
      'Silípica':['Silípica'],
    },
  },
  'Catamarca': {
    partidos: ['Capital','Belén','Santa María','Andalgalá','Tinogasta','La Paz','Fray Mamerto Esquiú','El Alto','Ambato','Pomán'],
    localidades: {
      'Capital':['San Fernando del Valle de Catamarca'],
      'Belén':['Belén'],
      'Santa María':['Santa María'],
      'Andalgalá':['Andalgalá'],
      'Tinogasta':['Tinogasta'],
      'La Paz':['Recreo'],
      'Fray Mamerto Esquiú':['Piedra Blanca'],
      'El Alto':['El Alto'],
      'Ambato':['Los Varela'],
      'Pomán':['Saujil'],
    },
  },
  'La Rioja': {
    partidos: ['Capital','Arauco','Famatina','Independencia','General Lamadrid','General San Martín','General Belgrano','Vinchina','San Blas de los Sauces','Coronel Felipe Varela'],
    localidades: {
      'Capital':['La Rioja'],
      'Arauco':['Aimogasta'],
      'Famatina':['Famatina'],
      'Independencia':['Patquía'],
      'General Lamadrid':['Chepes'],
      'General San Martín':['Guandacol'],
      'General Belgrano':['Villa Castelli'],
      'Vinchina':['Vinchina'],
      'San Blas de los Sauces':['San Blas de los Sauces'],
      'Coronel Felipe Varela':['Villa Unión'],
    },
  },
  'San Juan': {
    partidos: ['Capital','Chimbas','Rawson','Rivadavia','Santa Lucía','Caucete','San Martín','Pocito','Albardón','Angaco','Jáchal','Iglesia','Calingasta','Sarmiento','Valle Fértil','25 de Mayo','9 de Julio'],
    localidades: {
      'Capital':['San Juan'],
      'Chimbas':['Chimbas'],
      'Rawson':['Rawson'],
      'Rivadavia':['Rivadavia'],
      'Santa Lucía':['Santa Lucía'],
      'Caucete':['Caucete'],
      'San Martín':['San Martín'],
      'Pocito':['Villa Aberastain'],
      'Albardón':['San Isidro'],
      'Angaco':['Villa del Salvador'],
      'Jáchal':['Jáchal'],
      'Iglesia':['Rodeo'],
      'Calingasta':['Calingasta'],
      'Sarmiento':['Media Agua'],
      'Valle Fértil':['San Agustín del Valle Fértil'],
      '25 de Mayo':['25 de Mayo'],
      '9 de Julio':['Chucuma'],
    },
  },
  'San Luis': {
    partidos: ['La Capital','General Pedernera','Junín','Chacabuco','Coronel Pringles','Belgrano','Gobernador Dupuy','Aymaraes'],
    localidades: {
      'La Capital':['San Luis'],
      'General Pedernera':['Villa Mercedes'],
      'Junín':['Merlo','Carpintería','San Rafael'],
      'Chacabuco':['San Francisco del Monte de Oro'],
      'Coronel Pringles':['Tilisarao','Concarán'],
      'Belgrano':['La Toma'],
      'Gobernador Dupuy':['Buena Esperanza'],
      'Aymaraes':['Concarán'],
    },
  },
  'Neuquén': {
    partidos: ['Confluencia','Lácar','Los Lagos','Zapala','Chos Malal','Añelo','Aluminé','Huiliches','Pehuenches','Loncopué','Picunches','Minas','Collón Curá','Ñorquín','Picún Leufú'],
    localidades: {
      'Confluencia':['Neuquén','Centenario','Plottier','Vista Alegre'],
      'Lácar':['San Martín de los Andes'],
      'Los Lagos':['Villa La Angostura','Villa Traful'],
      'Zapala':['Zapala'],
      'Chos Malal':['Chos Malal'],
      'Añelo':['Añelo'],
      'Aluminé':['Aluminé'],
      'Huiliches':['Junín de los Andes'],
      'Pehuenches':['Rincón de los Sauces'],
      'Loncopué':['Loncopué'],
      'Picunches':['Las Lajas'],
      'Minas':['Andacollo'],
      'Collón Curá':['Piedra del Águila'],
      'Ñorquín':['Las Ovejas'],
      'Picún Leufú':['Picún Leufú'],
    },
  },
  'Río Negro': {
    partidos: ['Bariloche','General Roca','Adolfo Alsina','San Antonio','Pichi Mahuida','Avellaneda','Valcheta','Conesa','El Cuy','Nueve de Julio','Pilcaniyeu','Ñorquinco','Veinticinco de Mayo'],
    localidades: {
      'Bariloche':['San Carlos de Bariloche','El Bolsón'],
      'General Roca':['General Roca','Cipolletti','Allen','Cinco Saltos','Cervantes','Chichinales','Chimpay','Darwin','Godoy','Ingeniero Huergo','Luis Beltrán','Mainqué','Pomona','Villa Regina'],
      'Adolfo Alsina':['Viedma','Carmen de Patagones'],
      'San Antonio':['San Antonio Oeste','Las Grutas'],
      'Pichi Mahuida':['Río Colorado'],
      'Avellaneda':['Choele Choel'],
      'Valcheta':['Valcheta'],
      'Conesa':['General Conesa'],
      'El Cuy':['El Cuy'],
      'Nueve de Julio':['Maquinchao'],
      'Pilcaniyeu':['Pilcaniyeu'],
      'Ñorquinco':['Ñorquinco'],
      'Veinticinco de Mayo':['25 de Mayo'],
    },
  },
  'Chubut': {
    partidos: ['Rawson','Escalante','Biedma','Futaleufú','Gaimán','Sarmiento','Cushamen','Languiñeo','Mártires','Paso de Indios','Río Senguer','Tehuelches','Telsen'],
    localidades: {
      'Rawson':['Rawson','Trelew'],
      'Escalante':['Comodoro Rivadavia','Caleta Olivia'],
      'Biedma':['Puerto Madryn','Puerto Pirámides'],
      'Futaleufú':['Esquel','Trevelín'],
      'Gaimán':['Gaimán','Dolavon'],
      'Sarmiento':['Sarmiento'],
      'Cushamen':['El Maitén','Cholila'],
      'Languiñeo':['Tecka'],
      'Mártires':['Las Plumas'],
      'Paso de Indios':['Paso de Indios'],
      'Río Senguer':['Río Mayo'],
      'Tehuelches':['José de San Martín'],
      'Telsen':['Telsen'],
    },
  },
  'Santa Cruz': {
    partidos: ['Güer Aike','Deseado','Lago Argentino','Lago Buenos Aires','Corpen Aike','Río Chico','Magallanes','Lago Posadas'],
    localidades: {
      'Güer Aike':['Río Gallegos','Rospentek'],
      'Deseado':['Puerto Deseado','Las Heras','Pico Truncado','Caleta Olivia'],
      'Lago Argentino':['El Calafate','El Chaltén'],
      'Lago Buenos Aires':['Perito Moreno','Los Antiguos'],
      'Corpen Aike':['Comandante Luis Piedra Buena'],
      'Río Chico':['Gobernador Gregores'],
      'Magallanes':['Puerto San Julián'],
      'Lago Posadas':['Hipólito Yrigoyen'],
    },
  },
  'Tierra del Fuego': {
    partidos: ['Río Grande','Tolhuin','Ushuaia'],
    localidades: {
      'Río Grande':['Río Grande'],
      'Ushuaia':['Ushuaia'],
      'Tolhuin':['Tolhuin'],
    },
  },
  'La Pampa': {
    partidos: ['Capital','Maracó','General Acha','Loventué','Realicó','Chapaleufú','Rancul','Trenel','Conhelo','Quemú Quemú','Catriló','Guatraché','Toay','Atreucó','Hucal','Caleu Caleu','Chalileo','Puelén'],
    localidades: {
      'Capital':['Santa Rosa'],
      'Maracó':['General Pico'],
      'General Acha':['General Acha'],
      'Loventué':['Victorica'],
      'Realicó':['Realicó'],
      'Chapaleufú':['Intendente Alvear'],
      'Rancul':['Rancul'],
      'Trenel':['Trenel'],
      'Conhelo':['Eduardo Castex'],
      'Quemú Quemú':['Quemú Quemú'],
      'Catriló':['Catriló'],
      'Guatraché':['Guatraché'],
      'Toay':['Toay'],
      'Atreucó':['Macachín'],
      'Hucal':['Jacinto Arauz'],
      'Caleu Caleu':['La Adela'],
      'Chalileo':['Santa Isabel'],
      'Puelén':['Puelén'],
    },
  },
};

export default GEO_DATA;
